### PR TITLE
Replace AEMB parser with generic TSV parser

### PR DESCRIPTION
**Pull request by jakobnissen**
In issue 355, a user requested to bring back the --jgi option, suc that users can pass in precomputed abundances. That's completely reasonable, and it's not great that the currently recommended way is to use the internal Python types to create an Abundance object.

Instead of bringing back the JGI parser, I made a more generic TSV parser. TSV is a simple, straightforward format also used elsewhere in Vamb. Also, since it's easy to convert the output from --aemb to TSV format, I removed the --aemb option.

### CODE REVIEW

**Comment by GabeAl** [comment]
Superb. This is fantastic news. 
The --jgi format is also a tsv but includes variance estimates -- are these useful to include? Did/does VAMB make use of variance estimates in the same way metabat2 does? 

If so, it might make sense to allow an additional column per sample for the variance (as well as an overall, cross-sample column, like jgi). Of course if not -- then great, this is all we need!

**Comment by jakobnissen** [comment]
Vamb only uses the abundance itself, not the variance. We might want to add some more data in a future version, but for now, just the abundance values themselves are used.

**Comment by AroneyS** [comment]
Can this be added to a v4 release? Would be very helpful for including taxvamb in ensemble binning setups (e.g. https://github.com/rhysnewell/aviary).

**Comment by jakobnissen** [comment]
Do you mean v5? TaxVamb is part of v5, it does not exist in any v4 release.
This will be in Vamb v5. We don't have the bandwidth to backport features to older release branches, so this won't go in any v4 release.

**Pull request merged**
